### ISSUE TITLE
Error in requirements.txt

### ISSUE THREAD

**Issue by danielhers** [hasadna/open-shot#222]
Maybe the first line with the hyphen is the problem:
`- git+https://github.com/hasadna/django.git#egg=django`

Here is what I get:

```
$ pip install -r requirements.txt 
Exception:
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/oshot/local/lib/python2.7/site-packages/pip/basecommand.py", line 134, in main
    status = self.run(options, args)
  File "/home/daniel/.virtualenvs/oshot/local/lib/python2.7/site-packages/pip/commands/install.py", line 220, in run
    for req in parse_requirements(filename, finder=finder, options=options):
  File "/home/daniel/.virtualenvs/oshot/local/lib/python2.7/site-packages/pip/req.py", line 1456, in parse_requirements
    req = InstallRequirement.from_line(line, comes_from, prereleases=getattr(options, "pre", None))
  File "/home/daniel/.virtualenvs/oshot/local/lib/python2.7/site-packages/pip/req.py", line 127, in from_line
    return cls(req, comes_from, url=url, prereleases=prereleases)
  File "/home/daniel/.virtualenvs/oshot/local/lib/python2.7/site-packages/pip/req.py", line 43, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/home/daniel/.virtualenvs/oshot/local/lib/python2.7/site-packages/pkg_resources.py", line 2914, in parse
    reqs = list(parse_requirements(s))
  File "/home/daniel/.virtualenvs/oshot/local/lib/python2.7/site-packages/pkg_resources.py", line 2839, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "/home/daniel/.virtualenvs/oshot/local/lib/python2.7/site-packages/pkg_resources.py", line 2807, in scan_list
    raise ValueError("Expected "+item_name+" in",line,"at",line[p:])
ValueError: ('Expected version spec in', '- git+https://github.com/hasadna/django.git#egg=django', 'at', ' git+https://github.com/hasadna/django.git#egg=django')
```

**Comment by daonb** [comment]
errrrr. fixed it...
