### ISSUE TITLE
Login with Google: Server Error (500)

### ISSUE THREAD

**Issue by danielhers** [hasadna/open-shot#223]
After selecting a Google account, I am redirected to `http://localshot.org.il/complete/google-oauth2/` (with `state` and `code` parameters), and get a `Server Error (500)`.

Maybe related to this problem: http://stackoverflow.com/questions/16093305/django-social-auth-google-oauth-2-authcancelled-even-when-allow-access-is

**Comment by daonb** [comment]
It worked!

**Comment by danielhers** [comment]
Yeah, could be the same as #220 ...

**Comment by danielhers** [comment]
Just tried to login with Google and it didn't work. Got the server error.

**Comment by tbrisker** [comment]
Traceback (most recent call last):

  File "/home/oshot/src/oshot/ENV/src/django/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, _callback_args, *_callback_kwargs)

  File "/home/oshot/src/oshot/ENV/src/django/django/views/decorators/csrf.py", line 77, in wrapped_view
    return view_func(_args, *_kwargs)

  File "/home/oshot/src/oshot/ENV/local/lib/python2.7/site-packages/social_auth/decorators.py", line 29, in wrapper
    return func(request, request.social_auth_backend, _args, *_kwargs)

  File "/home/oshot/src/oshot/ENV/local/lib/python2.7/site-packages/social_auth/views.py", line 41, in complete
    return complete_process(request, backend, _args, *_kwargs)

  File "/home/oshot/src/oshot/ENV/local/lib/python2.7/site-packages/social_auth/views.py", line 107, in complete_process
    user = auth_complete(request, backend, _args, *_kwargs)

  File "/home/oshot/src/oshot/ENV/local/lib/python2.7/site-packages/social_auth/views.py", line 190, in auth_complete
    return backend.auth_complete(user=user, request=request, _args, *_kwargs)

  File "/home/oshot/src/oshot/ENV/local/lib/python2.7/site-packages/social_auth/backends/**init**.py", line 850, in auth_complete
    _args, *_kwargs)

  File "/home/oshot/src/oshot/ENV/local/lib/python2.7/site-packages/social_auth/backends/**init**.py", line 918, in do_auth
    return authenticate(_args, *_kwargs)

  File "/home/oshot/src/oshot/ENV/src/django/django/contrib/auth/**init**.py", line 60, in authenticate
    user = backend.authenticate(**credentials)

  File "/home/oshot/src/oshot/ENV/local/lib/python2.7/site-packages/social_auth/backends/**init**.py", line 107, in authenticate
    out = self.pipeline(pipeline, _args, *_kwargs)

  File "/home/oshot/src/oshot/ENV/local/lib/python2.7/site-packages/social_auth/backends/**init**.py", line 136, in pipeline
    result = func(_args, *_out) or {}

  File "/home/oshot/src/oshot/ENV/local/lib/python2.7/site-packages/social_auth/backends/pipeline/associate.py", line 21, in associate_by_email
    raise AuthException(kwargs['backend'], 'Not unique email address.')

AuthException: Not unique email address.
