### ISSUE TITLE
some users' public profiles cause a server error

### ISSUE THREAD

**Issue by tbrisker** [hasadna/open-shot#276]
Users known to cause this:
boaz.chen
lilib
לילי בן עמי
tal.kaufman
lolopipa
tami.shmuel1

Traceback (most recent call last):

  File "/home/oshot/src/oshot/ENV/src/django/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, _callback_args, *_callback_kwargs)

  File "/home/oshot/src/oshot/user/views.py", line 62, in public_profile
    return render(request, "user/public_profile.html", context)

  File "/home/oshot/src/oshot/ENV/src/django/django/shortcuts/**init**.py", line 53, in render
    return HttpResponse(loader.render_to_string(_args, *_kwargs),

  File "/home/oshot/src/oshot/ENV/src/django/django/template/loader.py", line 177, in render_to_string
    return t.render(context_instance)

  File "/home/oshot/src/oshot/ENV/src/django/django/template/base.py", line 140, in render
    return self._render(context)

  File "/home/oshot/src/oshot/ENV/src/django/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)

  File "/home/oshot/src/oshot/ENV/src/django/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)

  File "/home/oshot/src/oshot/ENV/src/django/django/template/base.py", line 844, in render_node
    return node.render(context)

  File "/home/oshot/src/oshot/ENV/src/django/django/template/loader_tags.py", line 124, in render
    return compiled_parent._render(context)

  File "/home/oshot/src/oshot/ENV/src/django/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)

  File "/home/oshot/src/oshot/ENV/src/django/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)

  File "/home/oshot/src/oshot/ENV/src/django/django/template/base.py", line 844, in render_node
    return node.render(context)

  File "/home/oshot/src/oshot/ENV/src/django/django/template/loader_tags.py", line 124, in render
    return compiled_parent._render(context)

  File "/home/oshot/src/oshot/ENV/src/django/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)

  File "/home/oshot/src/oshot/ENV/src/django/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)

  File "/home/oshot/src/oshot/ENV/src/django/django/template/base.py", line 844, in render_node
    return node.render(context)

  File "/home/oshot/src/oshot/ENV/src/django/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)

  File "/home/oshot/src/oshot/ENV/src/django/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)

  File "/home/oshot/src/oshot/ENV/src/django/django/template/base.py", line 844, in render_node
    return node.render(context)

  File "/home/oshot/src/oshot/ENV/src/django/django/template/defaulttags.py", line 424, in render
    raise e

NoReverseMatch: Reverse for 'local_home' with arguments '('',)' and keyword arguments '{}' not found.

**Comment by tbrisker** [comment]
caused by users who haven't selected a locality.

**Comment by lotan1** [comment]
קשור ל #277  ?
